### ISSUE TITLE
Support more than 5 dimensions in a JavaSeis dataset

### ISSUE THREAD

**Issue by samtkaplan** [ChevronETC/TeaSeis.jl#3]
Currently TeaSeis.jl supports 3,4 and 5 dimensional data-sets.  This was done for compatibility with existing software products.  Should TeaSeis.jl support data-sets with more than 5 dimensions and where the user just needs to be aware of compatibility issues?   This would require a trivial change to the following line of code: 

* https://github.com/ChevronETC/TeaSeis.jl/blob/8f098fc7e3c11527694399c4d04f1c371ad8e24a/src/teaseisio.jl#L233 

@chuckmosher, do you have any advice here?  Does the JavaSeis format specifically limit data-sets to be between 3 and 5 dimensions, or is that an implementation detail?

**Comment by chuckmosher** [comment]
Sam,

You are correct - SeisSpace only supports 5 dimensions, but the Seisio class in JavaSeis.org supports more than 5. Testing has been limited - up to 9 dimensions have been used in tests, but not in production.

Chuck

**Comment by samtkaplan** [comment]
Hi Chuck!

Thanks for the info. I will change TeaSeis to handle JavaSeis data-sets with more than 5 dimensions.  Thanks again for your help, and for making a nice data-format!

Sam
